language: ruby
sudo: false
cache: bundler
before_script:
  - bundle update
rvm:
  - 2.7
  - 2.6
  - 2.5

os:
  - linux
matrix:
  fast_finish: true
before_install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then brew install imagemagick; fi
script: bundle exec rake test
