language: ruby

cache: bundler
before_script:
  - gem install bundler:1.17.3
rvm:
  - 2.7
  - 2.6
  - 2.5

gemfile:
  - Gemfile
  - gemfiles/Gemfile.middleman-5.0-rc
  - gemfiles/Gemfile.middleman-4.3
  - gemfiles/Gemfile.middleman-4.2
  - gemfiles/Gemfile.middleman-4.1

jobs:
  fast_finish: true
  # We exclude these, since running Bundler 1 with Ruby 2.7 on Travis is not trivial, but Middleman 4.1/4.2 requires Bundler 1.
  exclude:
    - rvm: 2.7
      gemfile: gemfiles/Gemfile.middleman-4.2
    - rvm: 2.7
      gemfile: gemfiles/Gemfile.middleman-4.1

script: bundle exec rake test
